import { ExtractionPoint, TransitPoint } from '@/types/mapData';
import { WIKI_CONTENT } from './wikiData';

export const AVAILABLE_MAPS = [
  { id: 'ground_zero', name: 'Ground Zero', imagePath: '/maps/GroundZero.jpg' },
  { id: 'streets', name: 'Streets of Tarkov', imagePath: '/maps/StreetsOfTarkov.jpg' },
  { id: 'interchange', name: 'Interchange', imagePath: '/maps/Interchange.jpg' },
  { id: 'customs', name: 'Customs', imagePath: '/maps/Customs.jpg' },
  { id: 'factory', name: 'Factory', imagePath: '/maps/Factory.jpg' },
  { id: 'woods', name: 'Woods', imagePath: '/maps/Woods.jpg' },
  { id: 'reserve', name: 'Reserve', imagePath: '/maps/Reserve.jpg' },
  { id: 'lighthouse', name: 'Lighthouse', imagePath: '/maps/Lighthouse.jpg' },
  { id: 'shoreline', name: 'Shoreline', imagePath: '/maps/Shoreline.jpg' },
  { id: 'the_lab', name: 'The Lab', imagePath: '/maps/TheLab.jpg' },
  { id: 'the_labyrinth', name: 'The Labyrinth', imagePath: '/maps/The_Labyrinth.jpg' },
  { id: 'terminal', name: 'Terminal', imagePath: '/maps/Terminal.jpg' },
];

export const STATIC_EXTRACTS: Record<string, ExtractionPoint[]> = {
  ground_zero: [
    { id: 'gz-1', mapId: 'ground_zero', title: 'Emercom Checkpoint', description: 'South-east checkpoint.', conditions: [], coordinates: [500, 500], type: 'All' },
    { id: 'gz-2', mapId: 'ground_zero', title: 'Mira Ave', description: 'West side end of the street. Needs Green Flare.', conditions: ['Green Flare'], coordinates: [500, 500], type: 'PMC' },
    { id: 'gz-3', mapId: 'ground_zero', title: 'Nakatani Basement Stairs', description: 'North side, Nakatani building basement.', conditions: [], coordinates: [500, 500], type: 'All' },
    { id: 'gz-4', mapId: 'ground_zero', title: 'Police Cordon V-Ex', description: 'Black SUV near Police Station.', conditions: ['Roubles'], coordinates: [500, 500], type: 'PMC' },
    { id: 'gz-5', mapId: 'ground_zero', title: 'Scav Checkpoint', description: 'South side rubble area. Co-op.', conditions: ['Co-op'], coordinates: [500, 500], type: 'All' },
    { id: 'gz-6', mapId: 'ground_zero', title: 'Tartowers Sales Office', description: 'Needs item: Note with code word Adaptation.', conditions: ['Note with code word Adaptation'], coordinates: [500, 500], type: 'All' },
  ],
  streets: [
    { id: 'st-1', mapId: 'streets', title: 'Klimov Street', description: 'Near the green arch building. Needs Green Flare.', conditions: ['Green Flare'], coordinates: [500, 500], type: 'PMC' },
    { id: 'st-2', mapId: 'streets', title: 'Courtyard', description: 'Pinewood Hotel courtyard. Available if green smoke is present.', conditions: ['Green Smoke'], coordinates: [500, 500], type: 'PMC' },
    { id: 'st-3', mapId: 'streets', title: 'Primorsky Ave Taxi V-Ex', description: 'Black taxi on main avenue.', conditions: ['Roubles'], coordinates: [500, 500], type: 'PMC' },
    { id: 'st-4', mapId: 'streets', title: 'Stylobate Building Elevator', description: 'Elevator in stylobate building.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'st-5', mapId: 'streets', title: 'Sewer River', description: 'End of tram line, hole to underground.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'st-6', mapId: 'streets', title: 'Collapsed Crane', description: 'Near construction site.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'st-7', mapId: 'streets', title: 'Damaged House', description: 'Area with destroyed houses.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'st-8', mapId: 'streets', title: 'Crash Site', description: 'Crash site area.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'st-9', mapId: 'streets', title: 'Expo Checkpoint', description: 'Near Expo center.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'st-10', mapId: 'streets', title: 'Smugglers\' Basement', description: 'May need Note: Onyx.', conditions: ['Note: Onyx?'], coordinates: [500, 500], type: 'All' },
    { id: 'st-11', mapId: 'streets', title: 'Pinewood Basement', description: 'Pinewood hotel basement. Co-op.', conditions: ['Co-op'], coordinates: [500, 500], type: 'All' },
    // Scav extracts
    { id: 'st-s-1', mapId: 'streets', title: 'Cardinal Apartment Complex Parking', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'st-s-2', mapId: 'streets', title: 'Entrance to Catacombs', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'st-s-3', mapId: 'streets', title: 'Klimov Shopping Mall Exfil', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'st-s-4', mapId: 'streets', title: 'Near Kamchatskaya Arch', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'st-s-5', mapId: 'streets', title: 'Sewer Manhole', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'st-s-6', mapId: 'streets', title: 'Ventilation Shaft', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
  ],
  interchange: [
    { id: 'int-1', mapId: 'interchange', title: 'Emercom Checkpoint', description: 'South-east tent area. Dangerous.', conditions: [], coordinates: [500, 500], type: 'All' },
    { id: 'int-2', mapId: 'interchange', title: 'Path to River', description: 'Needs Green Flare.', conditions: ['Green Flare'], coordinates: [500, 500], type: 'PMC' },
    { id: 'int-3', mapId: 'interchange', title: 'Power Station V-Ex', description: 'SUV behind power station.', conditions: ['Roubles'], coordinates: [500, 500], type: 'PMC' },
    { id: 'int-4', mapId: 'interchange', title: 'Railway Exfil', description: 'North-west railway.', conditions: [], coordinates: [500, 500], type: 'All' },
    { id: 'int-5', mapId: 'interchange', title: 'Saferoom Exfil', description: 'Safe room. Needs #11SR keycard and power.', conditions: ['#11SR Key', 'Power On'], coordinates: [500, 500], type: 'PMC' },
    { id: 'int-6', mapId: 'interchange', title: 'Scav Camp', description: 'Highway containers. Co-op.', conditions: ['Co-op'], coordinates: [500, 500], type: 'All' },
    { id: 'int-7', mapId: 'interchange', title: 'Smugglers\' Tunnel', description: 'Needs Interchange underground utility plan.', conditions: ['Utility Plan'], coordinates: [500, 500], type: 'All' },
  ],
  customs: [
    { id: 'cus-1', mapId: 'customs', title: 'Crossroads', description: 'West side main extraction.', conditions: [], coordinates: [500, 500], type: 'All' },
    { id: 'cus-2', mapId: 'customs', title: 'ZB-1011', description: 'East side bunker.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'cus-3', mapId: 'customs', title: 'Old Gas Station', description: 'Needs Green Smoke.', conditions: ['Green Smoke'], coordinates: [500, 500], type: 'All' },
    { id: 'cus-4', mapId: 'customs', title: 'Dorms V-Ex', description: 'SUV at Dorms.', conditions: ['Roubles'], coordinates: [500, 500], type: 'PMC' },
    { id: 'cus-5', mapId: 'customs', title: 'Railroad Passage', description: 'Needs Green Flare.', conditions: ['Green Flare'], coordinates: [500, 500], type: 'PMC' },
    { id: 'cus-6', mapId: 'customs', title: 'Smuggler\'s Boat', description: 'Needs Note with code word Voron.', conditions: ['Note: Voron'], coordinates: [500, 500], type: 'All' },
    { id: 'cus-7', mapId: 'customs', title: 'ZB-1012', description: 'Needs Note with code word Voron.', conditions: ['Note: Voron'], coordinates: [500, 500], type: 'All' },
    { id: 'cus-8', mapId: 'customs', title: 'ZB-1013', description: 'New Gas basement. Needs Factory Key and Power.', conditions: ['Factory Key', 'Power On'], coordinates: [500, 500], type: 'PMC' },
    { id: 'cus-9', mapId: 'customs', title: 'Trailer Park', description: 'West side trailer park.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'cus-10', mapId: 'customs', title: 'Boiler Room Basement', description: 'Co-op extract.', conditions: ['Co-op'], coordinates: [500, 500], type: 'All' },
    // Scavs
    { id: 'cus-s-1', mapId: 'customs', title: 'Administration Gate', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-2', mapId: 'customs', title: 'Factory Far Corner', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-3', mapId: 'customs', title: 'Factory Shacks', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-4', mapId: 'customs', title: 'Military Base CP', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-5', mapId: 'customs', title: 'Old Gas Station Gate', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-6', mapId: 'customs', title: 'Old Road Gate', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-7', mapId: 'customs', title: 'Passage Between Rocks', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-8', mapId: 'customs', title: 'Railroad to Military Base', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-9', mapId: 'customs', title: 'Railroad to Port', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-10', mapId: 'customs', title: 'Railroad to Tarkov', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-11', mapId: 'customs', title: 'Scav Checkpoint', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-12', mapId: 'customs', title: 'Sniper Roadblock', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-13', mapId: 'customs', title: 'Trailer Park Workers\' Shack', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-14', mapId: 'customs', title: 'Warehouse 17', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'cus-s-15', mapId: 'customs', title: 'Warehouse 4', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
  ],
  factory: [
    { id: 'fac-1', mapId: 'factory', title: 'Gate 3', description: 'Main exit. Very dangerous.', conditions: [], coordinates: [500, 500], type: 'All' },
    { id: 'fac-2', mapId: 'factory', title: 'Gate 0', description: 'South side. Needs no conditions for PMC?', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'fac-3', mapId: 'factory', title: 'Cellars', description: 'Underground. Needs Factory Emergency Exit Key.', conditions: ['Factory Emergency Exit Key'], coordinates: [500, 500], type: 'PMC' },
    { id: 'fac-4', mapId: 'factory', title: 'Med Tent Gates', description: 'Needs Factory Emergency Exit Key.', conditions: ['Factory Emergency Exit Key'], coordinates: [500, 500], type: 'PMC' },
    { id: 'fac-5', mapId: 'factory', title: 'Courtyard Gate', description: 'Courtyard gate.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'fac-6', mapId: 'factory', title: 'Office Window', description: '3rd floor office window. Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'fac-7', mapId: 'factory', title: 'Camera Bunker Door', description: 'Underground bunker.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'fac-8', mapId: 'factory', title: 'Smugglers\' Passage', description: 'Needs Note with code word Ark.', conditions: ['Note: Ark'], coordinates: [500, 500], type: 'All' },
  ],
  woods: [
    { id: 'w-1', mapId: 'woods', title: 'Outskirts', description: 'West side main exit.', conditions: [], coordinates: [500, 500], type: 'All' },
    { id: 'w-2', mapId: 'woods', title: 'UN Roadblock', description: 'East side checkpoint.', conditions: [], coordinates: [500, 500], type: 'All' },
    { id: 'w-3', mapId: 'woods', title: 'Northern UN Roadblock', description: 'North-east checkpoint.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'w-4', mapId: 'woods', title: 'Bridge V-Ex', description: 'Village bridge SUV.', conditions: ['Roubles'], coordinates: [500, 500], type: 'PMC' },
    { id: 'w-5', mapId: 'woods', title: 'RUAF Gate', description: 'Needs Green Smoke.', conditions: ['Green Smoke'], coordinates: [500, 500], type: 'PMC' },
    { id: 'w-6', mapId: 'woods', title: 'RUAF Roadblock', description: 'Scav version of RUAF. Needs Green Smoke.', conditions: ['Green Smoke'], coordinates: [500, 500], type: 'Scav' },
    { id: 'w-7', mapId: 'woods', title: 'Power Line Passage', description: 'Needs Green Flare.', conditions: ['Green Flare'], coordinates: [500, 500], type: 'PMC' },
    { id: 'w-8', mapId: 'woods', title: 'ZB-014', description: 'Needs ZB-014 Key and Green Smoke.', conditions: ['Key', 'Green Smoke'], coordinates: [500, 500], type: 'PMC' },
    { id: 'w-9', mapId: 'woods', title: 'ZB-016', description: 'Needs Green Smoke.', conditions: ['Green Smoke'], coordinates: [500, 500], type: 'PMC' },
    { id: 'w-10', mapId: 'woods', title: 'Factory Gate', description: 'Co-op extract.', conditions: ['Co-op'], coordinates: [500, 500], type: 'All' },
    { id: 'w-11', mapId: 'woods', title: 'Friendship Bridge', description: 'Co-op extract.', conditions: ['Co-op'], coordinates: [500, 500], type: 'All' },
    // Scavs
    { id: 'w-s-1', mapId: 'woods', title: 'Dead Man\'s Place', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'w-s-2', mapId: 'woods', title: 'Eastern Rocks', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'w-s-3', mapId: 'woods', title: 'Mountain Stash', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'w-s-4', mapId: 'woods', title: 'Old Railway Depot', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'w-s-5', mapId: 'woods', title: 'Old Station', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'w-s-6', mapId: 'woods', title: 'Scav Bunker', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'w-s-7', mapId: 'woods', title: 'Scav House', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'w-s-8', mapId: 'woods', title: 'The Boat', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
  ],
  reserve: [
    { id: 'res-1', mapId: 'reserve', title: 'Cliff Descent', description: 'Dome cliff. Needs Red Rebel, Paracord, NO Body Armor.', conditions: ['Red Rebel', 'Paracord', 'No Armor'], coordinates: [500, 500], type: 'PMC' },
    { id: 'res-2', mapId: 'reserve', title: 'D-2', description: 'Underground bunker. Needs power ON.', conditions: ['Power On'], coordinates: [500, 500], type: 'PMC' },
    { id: 'res-3', mapId: 'reserve', title: 'Bunker Hermetic Door', description: 'Needs Siren (Lever) active.', conditions: ['Siren On'], coordinates: [500, 500], type: 'All' },
    { id: 'res-4', mapId: 'reserve', title: 'Armored Train', description: 'Train arrival.', conditions: ['Train'], coordinates: [500, 500], type: 'All' },
    { id: 'res-5', mapId: 'reserve', title: 'Sewer Manhole', description: 'No Backpack allowed.', conditions: ['No Backpack'], coordinates: [500, 500], type: 'All' },
    { id: 'res-6', mapId: 'reserve', title: 'Scav Lands', description: 'Co-op extract.', conditions: ['Co-op'], coordinates: [500, 500], type: 'All' },
    { id: 'res-7', mapId: 'reserve', title: 'Exit to Woods', description: 'Needs Minefield map (Reserve).', conditions: ['Minefield Map'], coordinates: [500, 500], type: 'All' },
    // Scavs
    { id: 'res-s-1', mapId: 'reserve', title: 'Checkpoint Fence', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'res-s-2', mapId: 'reserve', title: 'Depot Hermetic Door', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'res-s-3', mapId: 'reserve', title: 'Heating Pipe', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'res-s-4', mapId: 'reserve', title: 'Hole in the Fence by the Mountains', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
  ],
  lighthouse: [
    { id: 'lh-1', mapId: 'lighthouse', title: 'Southern Road', description: 'South end road.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'lh-2', mapId: 'lighthouse', title: 'Northern Checkpoint', description: 'North-west road end.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'lh-3', mapId: 'lighthouse', title: 'Path to Shoreline', description: 'East side mountains.', conditions: [], coordinates: [500, 500], type: 'All' },
    { id: 'lh-4', mapId: 'lighthouse', title: 'Mountain Pass', description: 'Needs Red Rebel, Paracord, No Armor.', conditions: ['Red Rebel', 'Paracord', 'No Armor'], coordinates: [500, 500], type: 'PMC' },
    { id: 'lh-5', mapId: 'lighthouse', title: 'Road to Military Base V-Ex', description: 'SUV east industrial area.', conditions: ['Roubles'], coordinates: [500, 500], type: 'PMC' },
    { id: 'lh-6', mapId: 'lighthouse', title: 'Passage by the Lake', description: 'Needs Minefield map (Lighthouse).', conditions: ['Minefield Map'], coordinates: [500, 500], type: 'All' },
    { id: 'lh-7', mapId: 'lighthouse', title: 'Armored Train', description: 'Train at Water Treatment Plant.', conditions: ['Train'], coordinates: [500, 500], type: 'All' },
    { id: 'lh-8', mapId: 'lighthouse', title: 'Side Tunnel', description: 'Co-op extract.', conditions: ['Co-op'], coordinates: [500, 500], type: 'All' },
    // Scav
    { id: 'lh-s-1', mapId: 'lighthouse', title: 'Hideout under the Landing Stage', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'lh-s-2', mapId: 'lighthouse', title: 'Industrial Zone Gates', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'lh-s-3', mapId: 'lighthouse', title: 'Scav Hideout at the Grotto', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'lh-s-4', mapId: 'lighthouse', title: 'Southern Road Landslide', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
  ],
  shoreline: [
    { id: 'sl-1', mapId: 'shoreline', title: 'Tunnel', description: 'South-west tunnel.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'sl-2', mapId: 'shoreline', title: 'Road to Customs', description: 'North-east gate.', conditions: [], coordinates: [500, 500], type: 'All' },
    { id: 'sl-3', mapId: 'shoreline', title: 'Path to Lighthouse', description: 'North-west swamp area.', conditions: [], coordinates: [500, 500], type: 'All' },
    { id: 'sl-4', mapId: 'shoreline', title: 'Pier Boat', description: 'Needs Green Smoke.', conditions: ['Green Smoke'], coordinates: [500, 500], type: 'PMC' },
    { id: 'sl-5', mapId: 'shoreline', title: 'Railway Bridge', description: 'Near railway.', conditions: [], coordinates: [500, 500], type: 'PMC' },
    { id: 'sl-6', mapId: 'shoreline', title: 'Road to North V-Ex', description: 'SUV north wall.', conditions: ['Roubles'], coordinates: [500, 500], type: 'PMC' },
    { id: 'sl-7', mapId: 'shoreline', title: 'Climber\'s Trail', description: 'Needs Red Rebel, Paracord, No Armor.', conditions: ['Red Rebel', 'Paracord', 'No Armor'], coordinates: [500, 500], type: 'PMC' },
    { id: 'sl-8', mapId: 'shoreline', title: 'Mountain Bunker', description: 'Needs Note with code word Heartbeat.', conditions: ['Note: Heartbeat'], coordinates: [500, 500], type: 'All' },
    { id: 'sl-9', mapId: 'shoreline', title: 'Smugglers\' Path', description: 'Co-op extract.', conditions: ['Co-op'], coordinates: [500, 500], type: 'All' },
    // Scav
    { id: 'sl-s-1', mapId: 'shoreline', title: 'Admin Basement', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'sl-s-2', mapId: 'shoreline', title: 'East Wing Gym Entrance', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'sl-s-3', mapId: 'shoreline', title: 'Lighthouse', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
    { id: 'sl-s-4', mapId: 'shoreline', title: 'Ruined Road', description: 'Scav only.', conditions: [], coordinates: [500, 500], type: 'Scav' },
  ],
  the_lab: [
    { id: 'lab-1', mapId: 'the_lab', title: 'Cargo Elevator', description: 'Needs power in G1.', conditions: ['Power G1'], coordinates: [500, 500], type: 'PMC' },
    { id: 'lab-2', mapId: 'the_lab', title: 'Hangar Gate', description: 'Needs control panel B24.', conditions: ['Panel B24'], coordinates: [500, 500], type: 'PMC' },
    { id: 'lab-3', mapId: 'the_lab', title: 'Main Elevator', description: 'Needs power near R4.', conditions: ['Power R4'], coordinates: [500, 500], type: 'PMC' },
    { id: 'lab-4', mapId: 'the_lab', title: 'Medical Block Elevator', description: 'Needs power G6.', conditions: ['Power G6'], coordinates: [500, 500], type: 'PMC' },
    { id: 'lab-5', mapId: 'the_lab', title: 'Parking Gate', description: 'Needs control panel Y21.', conditions: ['Panel Y21'], coordinates: [500, 500], type: 'PMC' },
    { id: 'lab-6', mapId: 'the_lab', title: 'Sewage Conduit', description: 'Needs water drainage.', conditions: ['Drain'], coordinates: [500, 500], type: 'PMC' },
    { id: 'lab-7', mapId: 'the_lab', title: 'Ventilation Shaft', description: 'No Backpack.', conditions: ['No Backpack'], coordinates: [500, 500], type: 'PMC' },
  ],
  the_labyrinth: [
    { id: 'laby-1', mapId: 'the_labyrinth', title: 'Ariadne\'s Path', description: 'Needs Ariadne symbol key.', conditions: ['Ariadne Key'], coordinates: [500, 500], type: 'All' },
    { id: 'laby-2', mapId: 'the_labyrinth', title: 'The Way Up', description: 'Available after 15 minutes.', conditions: ['>15 min'], coordinates: [500, 500], type: 'All' },
  ],
  terminal: [
    { id: 'term-1', mapId: 'terminal', title: 'Zubr Boat', description: 'Needs Task Item and 3 min survival.', conditions: ['Task Item', '3 min'], coordinates: [500, 500], type: 'All' },
  ],
};

export const TRANSIT_POINTS: Record<string, TransitPoint[]> = {
  ground_zero: [
    { id: 'gz-trs-1', mapId: 'ground_zero', destinationMapId: 'streets', description: 'To Streets: Beyond Mira Ave or near Sewer River.', coordinates: [500, 500] },
  ],
  streets: [
    { id: 'st-trs-1', mapId: 'streets', destinationMapId: 'interchange', description: 'To Interchange: NW Checkpoint.', coordinates: [500, 500] },
    { id: 'st-trs-2', mapId: 'streets', destinationMapId: 'the_lab', description: 'To The Lab: Boss area/underground.', coordinates: [500, 500] },
    { id: 'st-trs-3', mapId: 'streets', destinationMapId: 'ground_zero', description: 'To Ground Zero: Klimov/Sewer River.', coordinates: [500, 500] },
  ],
  interchange: [
    { id: 'int-trs-1', mapId: 'interchange', destinationMapId: 'customs', description: 'To Customs: Scav Camp highway.', coordinates: [500, 500] },
    { id: 'int-trs-2', mapId: 'interchange', destinationMapId: 'streets', description: 'To Streets: Railway Exfil road.', coordinates: [500, 500] },
  ],
  customs: [
    { id: 'cus-trs-1', mapId: 'customs', destinationMapId: 'factory', description: 'To Factory: Behind Old Gas Station.', coordinates: [500, 500] },
    { id: 'cus-trs-2', mapId: 'customs', destinationMapId: 'reserve', description: 'To Reserve: Near Military Base CP.', coordinates: [500, 500] },
    { id: 'cus-trs-3', mapId: 'customs', destinationMapId: 'interchange', description: 'To Interchange: Trailer Park road.', coordinates: [500, 500] },
    { id: 'cus-trs-4', mapId: 'customs', destinationMapId: 'shoreline', description: 'To Shoreline: Admin Gate area.', coordinates: [500, 500] },
  ],
  factory: [
    { id: 'fac-trs-1', mapId: 'factory', destinationMapId: 'woods', description: 'To Woods: Near Gate 3/Tunnel.', coordinates: [500, 500] },
    { id: 'fac-trs-2', mapId: 'factory', destinationMapId: 'customs', description: 'To Customs: Near Gate 0/Office.', coordinates: [500, 500] },
    { id: 'fac-trs-3', mapId: 'factory', destinationMapId: 'the_lab', description: 'To The Lab: Keycard point.', coordinates: [500, 500] },
  ],
  woods: [
    { id: 'w-trs-1', mapId: 'woods', destinationMapId: 'reserve', description: 'To Reserve: RUAF/UN Roadblock.', coordinates: [500, 500] },
    { id: 'w-trs-2', mapId: 'woods', destinationMapId: 'customs', description: 'To Customs: UN Roadblock/Factory Gate.', coordinates: [500, 500] },
    { id: 'w-trs-3', mapId: 'woods', destinationMapId: 'factory', description: 'To Factory: ZB-014 area.', coordinates: [500, 500] },
    { id: 'w-trs-4', mapId: 'woods', destinationMapId: 'lighthouse', description: 'To Lighthouse: Northern UN/Mountain.', coordinates: [500, 500] },
  ],
  reserve: [
    { id: 'res-trs-1', mapId: 'reserve', destinationMapId: 'customs', description: 'To Customs: North railyard.', coordinates: [500, 500] },
    { id: 'res-trs-2', mapId: 'reserve', destinationMapId: 'woods', description: 'To Woods: Scav Lands fields.', coordinates: [500, 500] },
    { id: 'res-trs-3', mapId: 'reserve', destinationMapId: 'lighthouse', description: 'To Lighthouse: Armored Train tracks.', coordinates: [500, 500] },
  ],
  lighthouse: [
    { id: 'lh-trs-1', mapId: 'lighthouse', destinationMapId: 'shoreline', description: 'To Shoreline: Path to Shoreline.', coordinates: [500, 500] },
    { id: 'lh-trs-2', mapId: 'lighthouse', destinationMapId: 'reserve', description: 'To Reserve: Road to Mil. Base.', coordinates: [500, 500] },
    { id: 'lh-trs-3', mapId: 'lighthouse', destinationMapId: 'woods', description: 'To Woods: Northern Checkpoint.', coordinates: [500, 500] },
  ],
  shoreline: [
    { id: 'sl-trs-1', mapId: 'shoreline', destinationMapId: 'lighthouse', description: 'To Lighthouse: Path to Lighthouse.', coordinates: [500, 500] },
    { id: 'sl-trs-2', mapId: 'shoreline', destinationMapId: 'terminal', description: 'To Terminal: 22:00-04:00 only.', coordinates: [500, 500] },
    { id: 'sl-trs-3', mapId: 'shoreline', destinationMapId: 'the_labyrinth', description: 'To The Labyrinth: Health Resort West Bsmt.', coordinates: [500, 500] },
  ],
  the_lab: [
    { id: 'lab-trs-1', mapId: 'the_lab', destinationMapId: 'streets', description: 'To Streets: Specific point.', coordinates: [500, 500] },
  ],
  the_labyrinth: [],
  terminal: [],
};

export { WIKI_CONTENT };
